AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3ObjectVersionParam:
    Type: String
Resources: 
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "dynamodb:DescribeTable"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            Resource:
              Fn::Sub:
              - "arn:aws:dynamodb:*:*:table/${LoanTableName}"
              - LoanTableName: !ImportValue LoanStreetTableName
          - Effect: Allow
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: "*"
  LoanStreetDynamoLambda: 
    Type: "AWS::Lambda::Function"
    Properties: 
      Handler: "index.handler"
      Role: 
        Fn::GetAtt: 
          - "LambdaExecutionRole"
          - "Arn"
      Runtime: "nodejs14.x"
      Code: 
        S3Bucket: !ImportValue LoanStreetLambdaBucket
        S3Key: lambda.zip
        S3ObjectVersion: !Ref S3ObjectVersionParam
Outputs:
  LoanStreetLambdaName:
    Value:
      !Ref LoanStreetDynamoLambda
    Export:
      Name: LoanStreetLambda
  Arn:
    Value:
      Fn::GetAtt:
        - LoanStreetDynamoLambda
        - Arn
  LamdbaExecutionRole:
    Value:
      !Ref LambdaExecutionRole
